export const GET_NEWS = "GET_NEWS";
export const CHANGE_TYPE_NEWS = "CHANGE_TYPE_NEWS";
export const CHANGE_COUNTRY_NEWS = "CHANGE_COUNTRY_NEWS";
export const ARCHIVED_NEWS = "ARCHIVED_NEWS";
export const DELETE_NEWS = "DELETE_NEWS";
